### PR TITLE
spelling: dynamic-columns

### PR DESCRIPTION
**Pull request by jsoref**
see SheetJS/test_files#4

### CODE REVIEW

**Comment by SheetJSDev** [comment]
This is true commitment :) Keep this PR and the test_files PR open for now, when we go back and update the test suite we'll push the changes and make the corresponding ones downstream

**Comment by jsoref** [comment]
The fanout from trying to fix a single repo is painful. I think I hit about 7 repos.

And that includes me skipping Node +  jQuery.
Thankfully my tools don't mind. Sadly, my brain gets fried, and it isn't easy to find the proper upstreams most of the time.

Thanks for working w/ me.

**Comment by SheetJSDev** [comment]
Instead of manually digging into the repos to understand their structure, you should consider asking the maintainers about the dependencies and related repos to inspect.

As for more active and high-profile projects like node and jQuery, you should simply raise an issue.  There are plenty of people looking to contribute to those projects.  Spell-checking is a great "first contribution"!

**Comment by jsoref** [comment]
Sometimes I do...
And yes, it is. I use it to see how healthy a project is and how well it manages contributions.

**Pull request merged**
